name: miccai_sim_unet_1d
device: cuda
starting_checkpoint:
pipeline:
  pipeline_name: diff
  model_name: unet_1d
  model_config: 
    input_channels: 2
    steps: 4
    initial_filters: 64
    kernel_size: 5
train:
  dataset_type: simulated
  data_file: data/simulated/train_data.h5
  transform: normal_noise
  weight_output_folder: miccai/saved_weights
  json_output_folder: miccai/train_jsons
  loss_fn: range_mae
  learning_rate: 0.005
  epochs: 200
  batch_size: 6
  scheduler_freq: 10
  early_stop: 10
  keep_best_treshold: 3
  force_stop: null
validation:
  dataset_type: invivo
  transform: accelerate
  data_file: data/splits/val_data_split_1.h5
  loss_fn: range_mae
test:
  dataset_type: invivo
  transform: accelerate
  data_file: data/splits/test_data_split_1.h5
  json_output_folder: miccai/test_jsons
  metrics:
    - mse
    - gaba_snr
    - gaba_linewidth
    - shape_score
inference:
  dataset_type: invivo
  transform: accelerate
  data_file: data/splits/test_data_split_1.h5